// Generated by extract_analyze.py — orchestrator (analyze) + table render + user picker.
// Imports from sibling modules + main.js.

import { RECIPES, NAMES } from "./config.js";
import { state } from "./state.js";
import { $, setStatus, clearDebug, renderDebug, escapeHtml } from "./utils.js";
import {
  _buildCache,
  fetchByUserId,
  fetchDirect,
  fetchViaPhp,
  renderBuildPanel,
} from "./_recovered.js";
export async function analyze(userId, usernameArg) {
  const query = usernameArg ?? $("username")["value"]["trim"]();
  if (!query && !userId) {
    setStatus("Insira um nome de usuário", "error");
    return;
  }
  (($("goBtn")["disabled"] = !![]),
    ($("results")["style"]["display"] = "none"),
    clearDebug(),
    _buildCache["clear"]());
  try {
    let data;
    if (userId) data = await fetchByUserId(userId);
    else
      try {
        data = await fetchViaPhp(query);
      } catch {
        data = await fetchDirect(query);
      }
    if (data["error"]) {
      setStatus(data["error"], "error");
      return;
    }
    if (data["needsPick"]) {
      renderUserPicker(data["query"], data["candidates"]);
      return;
    }
    if (!data["companies"] || data["companies"]["length"] === 0x0) {
      setStatus(
        (data["user"]?.["username"] || query) + " não tem empresas",
        "warn",
      );
      return;
    }
    render(data);
    const level = data["user"]?.["leveling"]?.["level"],
      userLabel =
        (data["user"]?.["username"] || query) +
        (level ? " lvl " + level : ""),
      truncatedNote = data["companiesTruncated"]
        ? " — ⚠ Bug de paginação da WarEra limitou a lista; o jogador pode ter mais empresas"
        : "";
    (setStatus(
      "Carregadas " +
        data["companies"]["length"] +
        " empresas de " +
        userLabel +
        truncatedNote,
      data["companiesTruncated"] ? "warn" : "",
    ),
      ($("buildBar")["style"]["display"] = "flex"),
      ($("buildDivider")["style"]["display"] = "block"));
  } catch (err) {
    let errDetail = "";
    if (err["kind"] === "network")
      errDetail =
        " — todos os hosts da API WarEra (api2/api6/api3/api4) estão inacessíveis. Causas comuns: (1) Cloudflare retornando 503 sem cabeçalhos CORS; (2) sua rede/VPN/bloqueador está bloqueando *.warera.io; (3) WarEra está fora do ar. Tente abrir a URL abaixo diretamente — se mostrar JSON, tente novamente; se mostrar erro, é queda da WarEra.";
    else {
      if (err["status"] >= 0x1f4)
        errDetail = " — API da WarEra instável. Tente novamente em um minuto.";
      else
        err["status"] >= 0x190 &&
          (errDetail =
            " — API rejeitou a requisição. Tente outro nome de usuário.");
    }
    (setStatus("Requisição falhou: " + err["message"] + errDetail, "error"),
      renderDebug(err));
  } finally {
    $("goBtn")["disabled"] = ![];
  }
}

export function renderUserPicker(query, candidates) {
  const buttonsHtml = candidates["map"](
      (candidate) =>
        '<button type="button" class="user-pick-btn" data-id="' +
        escapeHtml(candidate["id"]) +
        '" data-name="' +
        escapeHtml(candidate["username"]) +
        '">' +
        escapeHtml(candidate["username"]) +
        "</button>",
    )["join"](" "),
    statusEl = $("status");
  ((statusEl["className"] = "warn"),
    (statusEl["innerHTML"] =
      'Múltiplos usuários correspondem a "' +
      escapeHtml(query) +
      '" — escolha um: ' +
      buttonsHtml),
    statusEl["querySelectorAll"](".user-pick-btn")["forEach"]((btn) => {
      btn["addEventListener"]("click", () => {
        (($("username")["value"] = btn["dataset"]["name"]),
          analyze(btn["dataset"]["id"], btn["dataset"]["name"]));
      });
    }));
}

export function render(data) {
  const prices = data["prices"] || {},
    rows = [],
    workerScale = 0.24; // energy/10 actions per full bar × 2.4 bars/day = energy×0.24 actions/day
  let profitableCount = 0x0,
    processedCount = 0x0,
    rawCount = 0x0,
    totalWages = 0x0,
    totalWorkers = 0x0,
    totalAeNet = 0x0,
    activeAeNet = 0x0,
    activeAeCount = 0x0,
    totalWkNet = 0x0;
  const _ncOwn = {};
  const _ncCons = {};
  for (const _c of data.companies || []) {
    const _cd = _c.detail || {};
    const _cc = _cd.itemCode;
    const _cr = RECIPES[_cc];
    if (!_cr) continue;
    const _cb = (_c.bonus || {}).total || 0;
    const _cae =
      Math.floor((((_cd.activeUpgradeLevels || {}).automatedEngine || 0) *
        24 *
        (1 + _cb / 100)) /
      _cr.pp);
    const _caeCont = _cr.pp > 0
      ? ((_cd.activeUpgradeLevels || {}).automatedEngine || 0) * 24 * (1 + _cb / 100) / _cr.pp
      : 0;
    let _cwItems = 0,
      _cwWages = 0;
    for (const _w of _c.workers || []) {
      const _wf = _w.fidelity || 0;
      const _wpp =
        (_w.energy || 0) * (_w.production || 0) * (1 + _wf / 100 + _cb / 100) * workerScale;
      _cwItems += _cr.pp > 0 ? _wpp / _cr.pp : 0;
      _cwWages += (_wpp / (1 + _wf / 100 + _cb / 100)) * (_w.wage || 0);
    }
    const _ctotal = _cae + _cwItems;
    const _ctotalCons = _caeCont + _cwItems;
    if (!_ncOwn[_cc]) _ncOwn[_cc] = { u: 0, w: 0 };
    _ncOwn[_cc].u += _ctotal;
    _ncOwn[_cc].w += _cwWages;
    for (const _i of _cr.inputs) {
      _ncCons[_i.item] = (_ncCons[_i.item] || 0) + _ctotalCons * _i.amount;
    }
  }
  const _ncInt = {},
    _ncAC = {};
  for (const _k of Object.keys(_ncOwn)) {
    _ncInt[_k] = Math.min(_ncOwn[_k].u, _ncCons[_k] || 0);
    _ncAC[_k] = _ncOwn[_k].u > 0 ? _ncOwn[_k].w / _ncOwn[_k].u : 0;
  }
  const _ncRemaining = Object.fromEntries(Object.entries(_ncInt));
  for (const company of data["companies"]) {
    const detail = company["detail"] || {},
      itemCode = detail["itemCode"],
      recipe = RECIPES[itemCode];
    if (!recipe) continue;
    const bonus = company["bonus"]?.["total"] || 0x0,
      sellPrice = prices[itemCode] || 0x0;
    let matCost = 0x0;
    const inputParts = [];
    for (const inp of recipe["inputs"]) {
      const inpPrice = prices[inp["item"]] || 0x0;
      ((matCost += inpPrice * inp["amount"]),
        inputParts["push"](
          inp["amount"] + "× " + NAMES[inp["item"]],
        ));
    }
    const aeLevel =
        detail["activeUpgradeLevels"]?.["automatedEngine"] || 0x0,
      aePpDay = aeLevel * 0x18,
      aeItemsDay = Math.floor((aePpDay * (0x1 + bonus / 0x64)) / recipe["pp"]);
    (function () {
      let _ncM = 0;
      for (const _inp of recipe.inputs) {
        const _mkt = prices[_inp.item] || 0;
        const _extF = Math.max(
          0,
          1 -
            (_ncInt[_inp.item] || 0) /
              Math.max(_ncCons[_inp.item] || 0, 0.0001),
        );
        const _ac = _ncAC[_inp.item] || 0;
        _ncM += _inp.amount * (_extF * _mkt + (1 - _extF) * _ac);
      }
      matCost = _ncM;
    })();
    let aeNetDay = aeItemsDay * (sellPrice - matCost);
    let workerRows = (company["workers"] || [])["map"]((worker) => {
        const fidelity = worker["fidelity"] || 0x0,
          ppDay =
            (worker["energy"] || 0x0) *
            (worker["production"] || 0x0) *
            (1 + fidelity / 100 + bonus / 100) *
            workerScale,
          itemsDay = recipe["pp"] > 0x0 ? ppDay / recipe["pp"] : 0x0,
          wagePerPp = worker["wage"] || 0x0,
          wageDay =
            1 + fidelity / 100 + bonus / 100 > 0
              ? (wagePerPp * ppDay) / (1 + fidelity / 100 + bonus / 100)
              : 0x0,
          revenue = itemsDay * sellPrice,
          matCostDay = itemsDay * matCost,
          netDay = revenue - matCostDay - wageDay;
        return {
          username: worker["username"],
          level: worker["level"],
          energy: worker["energy"],
          production: worker["production"],
          fidelity: fidelity,
          wagePerPp: wagePerPp,
          ppDay: ppDay,
          itemsDay: itemsDay,
          wageDay: wageDay,
          netDay: netDay,
        };
      }),
      wkItems = workerRows["reduce"](
        (acc, wr) => acc + wr["itemsDay"],
        0x0,
      ),
      wkWages = workerRows["reduce"](
        (acc, wr) => acc + wr["wageDay"],
        0x0,
      ),
      wkNet = workerRows["reduce"](
        (acc, wr) => acc + wr["netDay"],
        0x0,
      );
    // Output adjustment: units consumed internally by other companies are valued
    // at atCost (wages/unit), not market price.
    // Denominator is _ncOwn[itemCode].u (all companies' total) so each company
    // only adjusts its proportional share of the internally-consumed output.
    const _outInt = _ncInt[itemCode] || 0;
    if (_outInt > 0) {
      const _totalOwn = (_ncOwn[itemCode] || {}).u || 0;
      if (_totalOwn > 0) {
        const _outAdj = _outInt * (sellPrice - (_ncAC[itemCode] || 0));
        aeNetDay -= _outAdj * (aeItemsDay / _totalOwn);
        wkNet -= _outAdj * (wkItems / _totalOwn);
      }
    }
    let profitDay = aeNetDay + wkNet;
    let isRaw = recipe["inputs"]["length"] === 0x0;
    if (isRaw) rawCount++;
    else processedCount++;
    if (profitDay > 0x0) profitableCount++;
    totalAeNet += aeNetDay;
    const aeActive = company["aeActive"] === !![];
    (aeActive && ((activeAeNet += aeNetDay), activeAeCount++),
      (totalWkNet += wkNet),
      (totalWages += wkWages),
      (totalWorkers += workerRows["length"]),
      rows["push"]({
        id: company["id"],
        name: detail["name"] || "(sem nome)",
        code: itemCode,
        isRaw: isRaw,
        bonus: bonus,
        sellPrice: sellPrice,
        inputParts: inputParts,
        suppliedInputs: recipe.inputs
          .map((inp) => {
            const ownProd = (_ncOwn[inp.item] || {}).u || 0;
            if (ownProd <= 0) return null;
            const companyDemand = (aeItemsDay + wkItems) * inp.amount;
            const available = _ncRemaining[inp.item] || 0;
            const supplied = Math.min(available, companyDemand);
            _ncRemaining[inp.item] = available - supplied;
            return { name: NAMES[inp.item] || inp.item, supplied, ownProd };
          })
          .filter(Boolean),
        matCostMarket: matCost,
        aeLevel: aeLevel,
        aeItemsDay: aeItemsDay,
        aeNetDay: aeNetDay,
        aeActive: aeActive,
        disabledAt: company["disabledAt"],
        workerRows: workerRows,
        workerItemsDay: wkItems,
        workerWageDay: wkWages,
        workerNetDay: wkNet,
        itemsDay: aeItemsDay + wkItems,
        profitDay: profitDay,
      }));
  }
  rows["sort"](
    (a, b) => b["profitDay"] - a["profitDay"],
  );
  const totalNet = totalAeNet + totalWkNet,
    avgNet = rows["length"] ? totalNet / rows["length"] : 0x0,
    skills = data["user"]?.["skills"] || {},
    entrepSkill = skills["entrepreneurship"]?.["total"] || 0x0,
    energySkill = skills["energy"]?.["total"] || 0x0,
    productionSkill = skills["production"]?.["total"] || 0x0,
    employer = data["employer"],
    energyProfitDay = employer
      ? (energySkill / 0xa) * productionSkill * 2.4 * employer["netWage"]
      : null;
  let bestEntrep = null;
  for (const row of rows) {
    const rowRecipe = RECIPES[row["code"]];
    if (!rowRecipe) continue;
    const entrepItemsDay =
        ((entrepSkill / 10) * productionSkill * (1 + row["bonus"] / 100) * 2.4) / rowRecipe["pp"],
      entrepProfitDay =
        entrepItemsDay * (row["sellPrice"] - row["matCostMarket"]);
    (!bestEntrep || entrepProfitDay > bestEntrep["profit"]) &&
      (bestEntrep = { profit: entrepProfitDay, companyName: row["name"] });
  }
  const energyCardHtml =
      energyProfitDay !== null
        ? '<div class="stat-card">\n                <div class="stat-label">Lucro energia / dia</div>\n                <div class="stat-value ' +
          (energyProfitDay >= 0x0 ? "positive" : "negative") +
          '">$' +
          energyProfitDay["toFixed"](0x2) +
          '</div>\n                <div class="stat-sub">$' +
          employer["netWage"]["toFixed"](0x3) +
          " líq. em " +
          escapeHtml(employer["companyName"]) +
          " (bônus " +
          employer["productionBonus"]["toFixed"](0x1) +
          "% · imposto " +
          employer["incomeTaxPct"] +
          "% · " +
          escapeHtml(employer["countryName"]) +
          ")</div>\n           </div>"
        : '<div class="stat-card">\n                <div class="stat-label">Lucro energia / dia</div>\n                <div class="stat-value muted">—</div>\n                <div class="stat-sub">sem empregador atual</div>\n           </div>',
    entrepCardHtml = bestEntrep
      ? '<div class="stat-card">\n                <div class="stat-label">Lucro empreend. / dia</div>\n                <div class="stat-value ' +
        (bestEntrep["profit"] >= 0x0 ? "positive" : "negative") +
        '">$' +
        bestEntrep["profit"]["toFixed"](0x2) +
        '</div>\n                <div class="stat-sub">melhor em ' +
        escapeHtml(bestEntrep["companyName"]) +
        "</div>\n           </div>"
      : '<div class="stat-card">\n                <div class="stat-label">Lucro empreend. / dia</div>\n                <div class="stat-value muted">—</div>\n           </div>',
    entrepProfit = bestEntrep ? bestEntrep["profit"] : 0x0,
    energyProfit = energyProfitDay ?? 0x0,
    grandTotal = entrepProfit + energyProfit + totalAeNet + totalWkNet,
    activeGrandTotal = entrepProfit + energyProfit + activeAeNet + totalWkNet;
  state.lastAnalysis = {
    user: data["user"],
    prices: data["prices"],
    employer: data["employer"],
    totals: {
      aeNet: totalAeNet,
      workersNet: totalWkNet,
      entrep: entrepProfit,
      energy: energyProfit,
      grand: grandTotal,
      avgPerCompany: avgNet,
      avgAePerCompany: rows["length"]
        ? totalAeNet / rows["length"]
        : 0x0,
      companyCount: rows["length"],
    },
  };
  if (state.activeBuild) renderBuildPanel();
  const grandTotalCss = grandTotal >= 0x0 ? "positive" : "negative",
    activeTotalCss = activeGrandTotal >= 0x0 ? "positive" : "negative",
    fmtProfit = (n) =>
      (n >= 0x0 ? "+$" : "-$") + Math["abs"](n)["toFixed"](0x2);
  (($("grandTotal")["innerHTML"] =
    '\n        <div class="grand-total-card">\n            <div>\n                <div class="gt-label">Lucro total / dia</div>\n                <div class="gt-value ' +
    grandTotalCss +
    '">' +
    fmtProfit(grandTotal) +
    '</div>\n                <div class="gt-subline">Lucro total ativo / dia <b class="' +
    activeTotalCss +
    '">' +
    fmtProfit(activeGrandTotal) +
    '</b></div>\n            </div>\n            <div class="gt-breakdown">\n                <span>Empreendedorismo <b>' +
    fmtProfit(entrepProfit) +
    "</b></span>\n                <span>Energia <b>" +
    fmtProfit(energyProfit) +
    "</b></span>\n                <span>Empresas (AE) <b>" +
    fmtProfit(totalAeNet) +
    "</b></span>\n                <span>Trabalhadores <b>" +
    fmtProfit(totalWkNet) +
    "</b></span>\n            </div>\n        </div>\n    "),
    ($("summaryPersonal")["innerHTML"] =
      '\n        <div class="stat-card"><div class="stat-label">Empreendedorismo</div><div class="stat-value">' +
      entrepSkill +
      '</div></div>\n        <div class="stat-card"><div class="stat-label">Energia</div><div class="stat-value">' +
      energySkill +
      '</div></div>\n        <div class="stat-card"><div class="stat-label">Produção</div><div class="stat-value">' +
      productionSkill +
      "</div></div>\n        " +
      entrepCardHtml +
      "\n        " +
      energyCardHtml +
      "\n    "),
    ($("personalLabel")["style"]["display"] = "block"),
    ($("summaryDivider")["style"]["display"] = "block"),
    ($("companiesLabel")["style"]["display"] = "block"));
  const mgmtLevel = skills["management"]?.["level"] || 0x0,
    mgmtSlots = skills["management"]?.["total"] || 0x4 + 0x2 * mgmtLevel;
  $("summary")["innerHTML"] =
    '\n        <div class="stat-card"><div class="stat-label">Empresas</div><div class="stat-value">' +
    rows["length"] +
    '</div></div>\n        <div class="stat-card"><div class="stat-label">Trabalhadores</div><div class="stat-value">' +
    totalWorkers +
    '<span class="muted" style="font-size:16px;font-weight:500;">/' +
    mgmtSlots +
    '</span></div><div class="stat-sub">nível de gestão ' +
    mgmtLevel +
    '</div></div>\n        <div class="stat-card"><div class="stat-label">Salários / dia</div><div class="stat-value negative">$' +
    totalWages["toFixed"](0x2) +
    '</div></div>\n        <div class="stat-card"><div class="stat-label">AE líq. / dia</div><div class="stat-value ' +
    (totalAeNet >= 0x0 ? "positive" : "negative") +
    '">$' +
    totalAeNet["toFixed"](0x2) +
    '</div><div class="stat-sub">todas as ' +
    rows["length"] +
    ' empresas</div></div>\n        <div class="stat-card"><div class="stat-label">AE líq. / dia (só ativas)</div><div class="stat-value ' +
    (activeAeNet >= 0x0 ? "positive" : "negative") +
    '">$' +
    activeAeNet["toFixed"](0x2) +
    '</div><div class="stat-sub">' +
    activeAeCount +
    "/" +
    rows["length"] +
    ' empresas ativas</div></div>\n        <div class="stat-card"><div class="stat-label">Trabalhadores líq. / dia</div><div class="stat-value ' +
    (totalWkNet >= 0x0 ? "positive" : "negative") +
    '">$' +
    totalWkNet["toFixed"](0x2) +
    '</div></div>\n        <div class="stat-card"><div class="stat-label">Líquido total / dia</div><div class="stat-value ' +
    (totalNet >= 0x0 ? "positive" : "negative") +
    '">$' +
    totalNet["toFixed"](0x2) +
    '</div></div>\n        <div class="stat-card"><div class="stat-label">Média líq. / dia por empresa</div><div class="stat-value ' +
    (avgNet >= 0x0 ? "positive" : "negative") +
    '">$' +
    avgNet["toFixed"](0x2) +
    "</div></div>\n    ";
  const tbody = $("tbody");
  ((tbody["innerHTML"] = rows["map"]((row) => {
    const typeTag = row["isRaw"]
        ? '<span class="tag raw">RAW</span>'
        : '<span class="tag processed">PROC</span>',
      disabledTag = row["aeActive"]
        ? ""
        : '<span class="tag aeoff" title="Empresa inativa' +
          (row["disabledAt"]
            ? " desde " + new Date(row["disabledAt"])["toLocaleString"]()
            : "") +
          ' — excluída do total ativo">INATIVA</span>',
      rowClass = row["aeActive"] ? "" : ' class="row-ae-off"',
      profitCss = row["profitDay"] >= 0x0 ? "positive" : "negative",
      aeNetCss = row["aeNetDay"] >= 0x0 ? "positive" : "negative",
      wkNetCss = row["workerNetDay"] >= 0x0 ? "positive" : "negative";
    let workerBtnHtml;
    row["workerRows"]["length"] === 0x0
      ? (workerBtnHtml = '<span class="muted">—</span>')
      : (workerBtnHtml =
          '<button class="expand-btn" data-target="w-' +
          row["id"] +
          '">' +
          row["workerRows"]["length"] +
          " ▾</button>");
    const rowHtml =
      "\n            <tr" +
      rowClass +
      ">\n                <td>" +
      escapeHtml(row["name"]) +
      disabledTag +
      "</td>\n                <td>" +
      (NAMES[row["code"]] || row["code"]) +
      " " +
      typeTag +
      "</td>\n                <td>" +
      row["bonus"]["toFixed"](0x2) +
      "%</td>\n                <td>" +
      row["aeLevel"] +
      "</td>\n                <td>" +
      row["aeItemsDay"]["toFixed"](0x1) +
      "</td>\n                <td>" +
      workerBtnHtml +
      "</td>\n                <td>" +
      row["workerItemsDay"]["toFixed"](0x1) +
      "</td>\n                <td>" +
      row["itemsDay"]["toFixed"](0x1) +
      "</td>\n                <td>$" +
      row["sellPrice"]["toFixed"](0x4) +
      '</td>\n                <td class="muted">' +
      (row["inputParts"]["length"]
        ? row["inputParts"]["join"](", ")
        : "—") +
      '</td>\n                <td class="muted">' +
      (row["suppliedInputs"]["length"]
        ? row["suppliedInputs"]["map"]((s) =>
            escapeHtml(s["name"]) + ": " + s["supplied"]["toFixed"](1) + "/" + s["ownProd"]["toFixed"](1)
          )["join"]("<br>")
        : "—") +
      "</td>\n                <td>$" +
      row["workerWageDay"]["toFixed"](0x2) +
      '</td>\n                <td class="' +
      aeNetCss +
      '">' +
      (row["aeNetDay"] >= 0x0 ? "+" : "") +
      "$" +
      row["aeNetDay"]["toFixed"](0x2) +
      '</td>\n                <td class="' +
      wkNetCss +
      '">' +
      (row["workerNetDay"] >= 0x0 ? "+" : "") +
      "$" +
      row["workerNetDay"]["toFixed"](0x2) +
      '</td>\n                <td class="profit-cell ' +
      profitCss +
      '">' +
      (row["profitDay"] >= 0x0 ? "+" : "") +
      "$" +
      row["profitDay"]["toFixed"](0x2) +
      "</td>\n            </tr>\n        ";
    if (row["workerRows"]["length"] === 0x0) return rowHtml;
    const workerDetailHtml =
      '\n            <tr class="worker-row" id="w-' +
      row["id"] +
      '" style="display:none;">\n                <td colspan="15">\n                    <div class="worker-block">\n                        <table class="worker-table">\n                            <thead><tr>\n                                <th>Trabalhador</th><th>Nível</th><th>Energia</th><th>Produção</th>\n                                <th>Sal./PP</th><th>Fidelidade</th>\n                                <th>PP/dia</th><th>Items/dia</th><th>Sal./dia</th><th>Líq./dia</th>\n                            </tr></thead>\n                            <tbody>\n                                ' +
      row["workerRows"]
        ["map"]((wr) => {
          const wrNetCss =
            wr["netDay"] >= 0x0 ? "positive" : "negative";
          return (
            "<tr>\n                                        <td>" +
            escapeHtml(wr["username"]) +
            "</td>\n                                        <td>" +
            wr["level"] +
            "</td>\n                                        <td>" +
            wr["energy"] +
            "</td>\n                                        <td>" +
            wr["production"] +
            "</td>\n                                        <td>$" +
            wr["wagePerPp"]["toFixed"](0x3) +
            "</td>\n                                        <td>" +
            wr["fidelity"] +
            "%</td>\n                                        <td>" +
            wr["ppDay"]["toFixed"](0x0) +
            "</td>\n                                        <td>" +
            wr["itemsDay"]["toFixed"](0x2) +
            "</td>\n                                        <td>$" +
            wr["wageDay"]["toFixed"](0x2) +
            '</td>\n                                        <td class="' +
            wrNetCss +
            '">' +
            (wr["netDay"] >= 0x0 ? "+" : "") +
            "$" +
            wr["netDay"]["toFixed"](0x2) +
            "</td>\n                                    </tr>"
          );
        })
        ["join"]("") +
      "\n                            </tbody>\n                        </table>\n                    </div>\n                </td>\n            </tr>\n        ";
    return rowHtml + workerDetailHtml;
  })["join"]("")),
    tbody["querySelectorAll"](".expand-btn")["forEach"]((btn) => {
      btn["addEventListener"]("click", () => {
        const targetRow = document["getElementById"](
          btn["dataset"]["target"],
        );
        if (!targetRow) return;
        const isOpen = targetRow["style"]["display"] !== "none";
        ((targetRow["style"]["display"] = isOpen ? "none" : "table-row"),
          (btn["textContent"] = btn["textContent"]["replace"](
            /[▾▴]/,
            isOpen ? "▾" : "▴",
          )));
      });
    }),
    ($("results")["style"]["display"] = "block"));
}
