// Generated by extract_state.py — mutable singleton state used across modules.
// Each module mutates `state.X` directly (object property write, NOT reassignment),
// so updates are visible across all importers.
//
// Only fields analyze.js shares with main.js are here for now; remaining state vars
// (_gearSnapshot, _buildCache, _minMaxStarted, …) live in main.js until 4b/c.

export const state = {
  lastAnalysis: null,
  activeBuild: null,
};
