// Generated by extract_utils.py — pure DOM/string helpers.
export const $ = (_0x56c7b0) => document["getElementById"](_0x56c7b0);
export const setStatus = (_0x48cf40, _0x2bc3cc = "") => {
    (($("status")["className"] = _0x2bc3cc),
      ($("status")["textContent"] = _0x48cf40));
  };

export const clearDebug = () => {
  $("debug")["innerHTML"] = "";
};

export function renderDebug(_0x37adf9) {
  const _0x507b44 = [
      ["error.name", _0x37adf9?.["name"] || "(unknown)"],
      ["error.message", _0x37adf9?.["message"] || "(empty)"],
      [
        "kind",
        _0x37adf9?.["kind"] ||
          (_0x37adf9?.["status"]
            ? "http " + _0x37adf9["status"]
            : "(unclassified)"),
      ],
      ["tRPC path", _0x37adf9?.["path"] || "(n/a)"],
    ],
    _0x4c0b0d = _0x37adf9?.["url"] || "",
    _0x3fbc2c = _0x4c0b0d
      ? '<b>request URL</b><span><a href="' +
        _0x4c0b0d +
        '" target="_blank" rel="noopener">' +
        _0x4c0b0d +
        "</a></span>"
      : "",
    _0x3ba953 =
      _0x507b44["map"](
        ([_0xb2ebe8, _0x569dfa]) =>
          "<b>" +
          _0xb2ebe8 +
          "</b><span>" +
          String(_0x569dfa)["replace"](
            /[<&>]/g,
            (_0x4c1005) =>
              ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" })[_0x4c1005],
          ) +
          "</span>",
      )["join"]("") + _0x3fbc2c;
  $("debug")["innerHTML"] =
    '\n        <details open>\n            <summary>Debug info (click to collapse)</summary>\n            <div class="kv">' +
    _0x3ba953 +
    '</div>\n            <div style="margin-top:8px; font-size:11px; color:#888;">\n                Tip: open the request URL in a new tab. JSON = API alive (re-run the tool); HTML/error page = WarEra outage.\n                Also check DevTools Network tab for the actual HTTP status (often hidden from JS when CORS headers are missing).\n            </div>\n        </details>';
}

export function escapeHtml(_0x324dbf) {
  return String(_0x324dbf)["replace"](
    /[&<>"']/g,
    (_0xe81012) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        _0xe81012
      ],
  );
}
